name: Gradle CI

on:
  push:
    paths:
      - 'gradle/build.gradle'
      - 'allow-list.xml'
      - '.github/workflows/gradle.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Scan for CVEs
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: dependencyCheckAnalyze
        working-directory: gradle